# Tutorial used here: https://www.youtube.com/watch?v=BEki_rsWu4E

Domain: Eukarya
Kingdom: Animalia
Phylum: Chordata
Class: Mammalia
Order: Carnivora
Family: Ursidae
Genus: Ursus
Species: Ursus Americanus

Description: > 
  Omnivorous bear characterized by a black coat and brown snout.

Diet:
    -Honey
    -Fruit
    -Insects
    -Salmon
    -Carrion
    -Caribou