---
#
# This docker-compose.yml is for running the latest development version
# of An Otter Wiki.
#
# Please read the Installation guide <https://otterwiki.com/Installation>
# to get started.
#

services:
  otterwiki:
    image: redimp/otterwiki:2
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./app-data:/app-data
  # mount the local directory ./app-data into the container
      # (so settings, database and repository are accessible)

