---
services:
  wikijs:
    image: lscr.io/linuxserver/wikijs:2.5.311
    container_name: wikijs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DB_TYPE=sqlite #optional
      - DB_HOST= #optional
      - DB_PORT= 8000
      - DB_NAME= #optional
      - DB_USER= #optional
      - DB_PASS= #optional
    volumes:
      - ./website-files:/usr/share/nginx/html:ro
      - /Sprint2/:/usr/share/nginx/html/
    ports:
      - 3000:3000
    restart: unless-stopped
